version: '3'
services:
  app:
    #app_goの中にあるDockerfileの読み込み
    build: ./app_go
    container_name: "app_go"
    tty: true
    #ホストのディレクトリをコンテナにマウント
    volumes:
      - ./app_go:/go/src/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/Godb?sslmode=disable
    links: 
      - postgres:postgres
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Godb
      - TZ=Asia/Tokyo
    tty: true
    restart: always
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
 

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/Godb?sslmode=disable
    links: 
      - postgres:postgres
    restart: always
    depends_on:
      - postgres

volumes:
  dbdata:
    external: false